In [2]:
import torch
from torch import nn

/home/tignjatov/anaconda3/envs/ml/lib/python3.6/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [37]:
transformer_model = nn.Transformer(nhead=16, num_encoder_layers=12)
embedding_src = nn.Embedding(num_embeddings=10, embedding_dim=512)
embedding_trg = nn.Embedding(num_embeddings=10, embedding_dim=512)
src = torch.rand((39, 32)).long()
tgt = torch.rand((20, 32)).long()
out_src = embedding_src(src)
out_trg = embedding_trg(tgt)

In [20]:
out_src.shape

torch.Size([39, 32, 512])

In [21]:
out_trg.shape

torch.Size([20, 32, 512])

In [33]:
out = transformer_model(out_src, out_trg,tgt_mask = out_trg_mask)

In [29]:
out_trg_mask = transformer_model.generate_square_subsequent_mask(out_trg.shape[0])

In [35]:
out.shape

torch.Size([20, 32, 512])

In [30]:
x = torch.rand(20,32)

In [31]:
y = torch.rand(32)

In [32]:
x.shape

torch.Size([20, 32])

In [34]:
y=y.reshape(1,32)

In [36]:
torch.concat((x,y)).shape

torch.Size([21, 32])

In [38]:
torch.tensor([1])

tensor([1])

In [29]:
src = torch.tensor([[1,0,0,0,1],[1,2,2,2,1]])

In [30]:
src

tensor([[1, 0, 0, 0, 1],
        [1, 2, 2, 2, 1]])

In [33]:
(src == 0).transpose(0,1)

tensor([[False, False],
        [ True, False],
        [ True, False],
        [ True, False],
        [False, False]])

In [36]:
torch.zeros((2,2)).type(torch.bool)

tensor([[False, False],
        [False, False]])

In [39]:
def generate_square_subsequent_mask(sz):
    mask = (torch.triu(torch.ones((sz, sz))) == 1).transpose(0, 1)
    mask = mask.float().masked_fill(mask == 0, float('-inf')).masked_fill(mask == 1, float(0.0))
    return mask

In [47]:
def create_mask(src, tgt):
    src_seq_len = src.shape[0]
    tgt_seq_len = tgt.shape[0]

    tgt_mask = generate_square_subsequent_mask(tgt_seq_len)
    src_mask = torch.zeros((src_seq_len, src_seq_len)).type(torch.bool)

    src_padding_mask = (src == 0).transpose(0, 1)
    tgt_padding_mask = (tgt == 1).transpose(0, 1)
    return src_mask, tgt_mask, src_padding_mask, tgt_padding_mask

In [42]:
x = generate_square_subsequent_mask(src.shape[0]) == transformer_model.generate_square_subsequent_mask(src.shape[0])

In [44]:
x.unique()

tensor([True])

In [73]:
src_mask, tgt_mask, src_padding_mask, tgt_padding_mask = create_mask(src, tgt)

In [80]:
torch.tensor([1,0,0,0,1]).view(-1,1)

tensor([[1],
        [0],
        [0],
        [0],
        [1]])

In [68]:
src = torch.tensor([[1,5,3,6,1]])
src.shape

torch.Size([1, 5])

In [69]:
tgt = torch.tensor([[1]])

In [74]:
src_mask

tensor([[False]])

In [96]:
ys = torch.ones(1,1).fill_(1).type(torch.long)

In [98]:
torch.cat([ys,torch.ones(1, 1).type_as(src.data).fill_(torch.tensor(5))], dim=0)

tensor([[1],
        [5]])

In [101]:
torch.ones(1, 1).type_as(src.data).fill_(torch.tensor(5))

tensor([[5]])